-- Create total_tva table
CREATE TABLE public.total_tva (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  date DATE,
  numero_facture TEXT,
  vendeur TEXT,
  montant_ttc NUMERIC,
  tva_20 NUMERIC,
  tva_10 NUMERIC,
  tva_5_5 NUMERIC,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE public.total_tva ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Users can view their own TVA data" 
ON public.total_tva 
FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own TVA data" 
ON public.total_tva 
FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own TVA data" 
ON public.total_tva 
FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own TVA data" 
ON public.total_tva 
FOR DELETE 
USING (auth.uid() = user_id);

-- Enable realtime
ALTER TABLE public.total_tva REPLICA IDENTITY FULL;
ALTER PUBLICATION supabase_realtime ADD TABLE public.total_tva;